### ISSUE TITLE
have an option to click on a particular leaderboard entry to expand and see full parameters from the JSON output

### ISSUE THREAD

**Issue by pooja** [filecoin-project/replication-game-leaderboard#2]
Currently each leaderboard entry only displays the replication time. Would be great to be able to click on a particular entry to expand the full entry which includes all the parameters that were run in order to generate that replication time. It should include all the other parameters included in the JSON output for completeness! Also, should be able to click on the entry to minimize the full detail view as well.

This could be a good way to address @dignifiedquire's note that the different parameters will also lead to different proving times. While we figure out a nice way to display that elegantly, having click to expand parameters will be nice! (And perhaps even after we find a way to display that elegantly.)

**Comment by alanshaw** [comment]
Resolved by https://github.com/filecoin-project/replication-game-leaderboard/pull/15 where we've grouped into mulltiple leaderboards that display all the parameters.
