### ISSUE TITLE
Align colors to branding

### ISSUE THREAD

**Issue by alanshaw** [filecoin-project/replication-game-leaderboard#9]
From feedback on https://github.com/filecoin-project/replication-game-leaderboard/pull/5 from @pooja:

> One request (maybe for another PR), would you be able to align the colors to those of our brand card? I think the medals are great, but maybe we can have the boxes around each submission be colors that are closer to our brand colors. Brand card is [here](https://user-images.githubusercontent.com/22168118/52518635-d8a05180-2c4d-11e9-90ac-90b02f260c3c.png) Let me know if you can't see it!

**Comment by alanshaw** [comment]
FWIW the background blue is the same as what is currently on the filecoin.io website:

<img width="1316" alt="screenshot 2019-03-01 at 18 09 29" src="https://user-images.githubusercontent.com/152863/53657142-36bcc500-3c4d-11e9-97e7-ade3c4e93fd8.png">

...and Gold/Silver/Bronze colouring for the winners can't easily be aligned to the brand!

I did have a quick go at making this black and purple but I think it looks horrible:

<img width="839" alt="screenshot 2019-03-01 at 18 12 10" src="https://user-images.githubusercontent.com/152863/53657268-a2069700-3c4d-11e9-961c-2d3bed876589.png">

**Comment by pooja** [comment]
No worries at all. Feel free to leave it as is. I think it looks great!
